-- Create quotations table
CREATE TABLE quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_number TEXT UNIQUE NOT NULL,
    date DATE NOT NULL,
    customer_name TEXT NOT NULL,
    customer_mobile TEXT,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount NUMERIC(12, 2) DEFAULT 0,
    tax NUMERIC(12, 2) DEFAULT 0,
    shipping_charge NUMERIC(12, 2) DEFAULT 0,
    grand_total NUMERIC(12, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'done')),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Create quotation_items table
CREATE TABLE quotation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quotation_id BIGINT REFERENCES quotations(id) ON DELETE CASCADE,
    item_id BIGINT REFERENCES items(id),
    quantity NUMERIC NOT NULL,
    selling_price NUMERIC(12, 2) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL
);

-- Add quotation_id to sales table to track converted quotations
ALTER TABLE sales ADD COLUMN quotation_id BIGINT REFERENCES quotations(id);

-- Function to generate quotation number
CREATE OR REPLACE FUNCTION generate_quotation_number()
RETURNS TRIGGER AS $$
BEGIN
    NEW.quotation_number := 'QT-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(cast(floor(random() * 10000) as text), 4, '0');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_generate_quotation_number
BEFORE INSERT ON quotations
FOR EACH ROW
EXECUTE FUNCTION generate_quotation_number();

-- RPC to create quotation
CREATE OR REPLACE FUNCTION create_quotation(
    p_customer_name TEXT,
    p_customer_mobile TEXT,
    p_date DATE,
    p_discount NUMERIC,
    p_tax NUMERIC,
    p_shipping_charge NUMERIC,
    p_items JSONB
) RETURNS BIGINT AS $$
DECLARE
    v_quotation_id BIGINT;
    v_item RECORD;
    v_subtotal NUMERIC := 0;
BEGIN
    -- Calculate subtotal from items
    FOR v_item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(item_id BIGINT, quantity NUMERIC, selling_price NUMERIC)
    LOOP
        v_subtotal := v_subtotal + (v_item.quantity * v_item.selling_price);
    END LOOP;

    INSERT INTO quotations (
        date,
        customer_name,
        customer_mobile,
        subtotal,
        discount,
        tax,
        shipping_charge,
        grand_total
    ) VALUES (
        p_date,
        p_customer_name,
        p_customer_mobile,
        v_subtotal,
        p_discount,
        p_tax,
        p_shipping_charge,
        (v_subtotal - p_discount + p_tax + p_shipping_charge)
    ) RETURNING id INTO v_quotation_id;

    -- Insert items
    FOR v_item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(item_id BIGINT, quantity NUMERIC, selling_price NUMERIC)
    LOOP
        INSERT INTO quotation_items (quotation_id, item_id, quantity, selling_price, amount)
        VALUES (v_quotation_id, v_item.item_id, v_item.quantity, v_item.selling_price, v_item.quantity * v_item.selling_price);
    END LOOP;

    RETURN v_quotation_id;
END;
$$ LANGUAGE plpgsql;

-- RPC to convert quotation to sale
CREATE OR REPLACE FUNCTION convert_quotation_to_sale(
    p_quotation_id BIGINT
) RETURNS BIGINT AS $$
DECLARE
    v_quotation RECORD;
    v_sale_id BIGINT;
    v_q_item RECORD;
    v_item_details RECORD;
BEGIN
    -- Get quotation details
    SELECT * INTO v_quotation FROM quotations WHERE id = p_quotation_id;

    IF v_quotation.status != 'done' THEN
        RAISE EXCEPTION 'Only quotations marked as "done" can be converted to a bill.';
    END IF;

    -- Create sale
    INSERT INTO sales (
        bill_number,
        date,
        customer_name,
        customer_mobile,
        subtotal,
        discount,
        tax,
        shipping_charge,
        grand_total,
        quotation_id
    ) VALUES (
        'BILL-' || to_char(now(), 'YYYYMMDD') || '-' || lpad(cast(floor(random() * 10000) as text), 4, '0'),
        v_quotation.date,
        v_quotation.customer_name,
        v_quotation.customer_mobile,
        v_quotation.subtotal,
        v_quotation.discount,
        v_quotation.tax,
        v_quotation.shipping_charge,
        v_quotation.grand_total,
        p_quotation_id
    ) RETURNING id INTO v_sale_id;

    -- Insert sale items and update stock
    FOR v_q_item IN SELECT * FROM quotation_items WHERE quotation_id = p_quotation_id
    LOOP
        -- Get item details for profit and weight
        SELECT purchase_price, shipping_weight INTO v_item_details FROM items WHERE id = v_q_item.item_id;

        INSERT INTO sale_items (
            sale_id,
            item_id,
            quantity,
            selling_price,
            purchase_price,
            shipping_weight,
            amount,
            profit
        ) VALUES (
            v_sale_id,
            v_q_item.item_id,
            v_q_item.quantity,
            v_q_item.selling_price,
            v_item_details.purchase_price,
            v_item_details.shipping_weight,
            v_q_item.amount,
            (v_q_item.selling_price - v_item_details.purchase_price) * v_q_item.quantity
        );

        -- Update stock
        UPDATE items
        SET current_stock = current_stock - v_q_item.quantity
        WHERE id = v_q_item.item_id;
    END LOOP;

    RETURN v_sale_id;
END;
$$ LANGUAGE plpgsql;
